version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  # cypress:
  #   # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
  #   image: "cypress/included:12.6.0"
  #   depends_on:
  #     - web
  #   environment:
  #     # pass base url to test pointing at the web application
  #     - CYPRESS_baseUrl=http://web:3000
  #   # share the current folder as volume to avoid copying
  #   working_dir: /e2e
  #   volumes:
  #     - ./:/e2e
  #   # run the tests
  #   command: npm run e2etest
